#
# The contents of this file are subject to the Apache 2.0 license you may not
# use this file except in compliance with the License.
#
# Software distributed under the License is distributed on an "AS IS" basis,
# WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
# for the specific language governing rights and limitations under the
# License.
#
#
# Copyright 2016 DFT project (http://www.firmwaretoolkit.org).
# All rights reserved. Use is subject to license terms.
#
# Debian Firmware Toolkit is the new name of Linux Firmware From Scratch
# Copyright 2014 LFFS project (http://www.linuxfirmwarefromscratch.org).
#
#
# Contributors list :
#
#    William Bonnet     wllmbnnt@gmail.com, wbonnet@theitmakers.com
#
#

---

#
# Install Xfce packages needed to have a desktop session
#
- name : DFT - Install Xfce4 desktop
  apt: name={{ item }}
       state=latest
       install_recommends=no
  with_items:
    - xfce4
    - gnome-themes-standard
    - gnome-themes-standard-data
    - task-xfce-desktop
    - xfce4-appfinder
    - xfce4-battery-plugin
    - xfce4-clipman
    - xfce4-clipman-plugin
    - xfce4-cpufreq-plugin
    - xfce4-cpugraph-plugin
    - xfce4-datetime-plugin
    - xfce4-dict
    - xfce4-diskperf-plugin
    - xfce4-fsguard-plugin
    - xfce4-genmon-plugin
    - xfce4-mailwatch-plugin
    - xfce4-mount-plugin
    - xfce4-netload-plugin
    - xfce4-notes
    - xfce4-notes-plugin
    - xfce4-notifyd
    - xfce4-panel
    - xfce4-places-plugin
    - xfce4-power-manager
    - xfce4-power-manager-data
    - xfce4-power-manager-plugins
    - xfce4-pulseaudio-plugin
    - xfce4-screenshooter
    - xfce4-sensors-plugin
    - xfce4-session
    - xfce4-settings
    - xfce4-smartbookmark-plugin
    - xfce4-systemload-plugin
    - xfce4-taskmanager
    - xfce4-terminal
    - xfce4-timer-plugin
    - xfce4-verve-plugin
    - xfce4-wavelan-plugin
    - xfce4-weather-plugin
    - xfce4-whiskermenu-plugin
    - xfce4-xkb-plugin
    - gnome-icon-theme 
    - gnome-icon-theme-symbolic
    - tango-icon-theme
