#
# The contents of this file are subject to the Apache 2.0 license you may not
# use this file except in compliance with the License.
#
# Software distributed under the License is distributed on an "AS IS" basis,
# WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
# for the specific language governing rights and limitations under the
# License.
#
#
# Copyright 2020 DFT project (http://www.firmwaretoolkit.org).
# All rights reserved. Use is subject to license terms.
#
#
# Contributors list :
#
#    William Bonnet     wllmbnnt@gmail.com, wbonnet@theitmakers.com
#
#

---
- name : DFT - Setup /etc/fstab
  template: src=fstab.j2
            dest=/etc/fstab
            owner=root
            group=root
            mode="0660"
  # Excute this task only if the filesystems variable is defined
  with_items: "{{ dft_os_fstab.filesystems }}"
  when: dft_os_fstab.filesystems is defined


