#
# The contents of this file are subject to the Apache 2.0 license you may not
# use this file except in compliance with the License.
#
# Software distributed under the License is distributed on an "AS IS" basis,
# WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
# for the specific language governing rights and limitations under the
# License.
#
#
# Copyright 2020 DFT project (http://www.firmwaretoolkit.org).
# All rights reserved. Use is subject to license terms.
#
#
# Contributors list :
#
#    William Bonnet     wllmbnnt@gmail.com, wbonnet@theitmakers.com
#
#

---
# Execute this task only if filesystems variable is defined in inventory
- name: Create filesystems mount points
  file:
    path:  "{{ item.path }}"
    state: directory
    owner: root
    group: root
    mode: "{{ item.mode | default('0755') }}"
  loop: "{{ dft_os_fstab.filesystems|flatten }}"

# Set the filesystem mount status according to inventory
- name: Mount filesystems
  mount:
    boot: "{{ item.boot | default(True) }}"
    dump: "{{ item.dump | default(0) }}"
    fstype: "{{ item.fstype }}"
    opts: "{{ item.opts }}"
    passno: "{{ item.passno | default (2) }}"
    src: "{{ item.src }}"
    path:  "{{ item.path }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ dft_os_fstab.filesystems|flatten }}"
