#
# The contents of this file are subject to the Apache 2.0 license you may not
# use this file except in compliance with the License.
#
# Software distributed under the License is distributed on an "AS IS" basis,
# WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
# for the specific language governing rights and limitations under the
# License.
#
#
# Copyright 2020 DFT project (http://www.firmwaretoolkit.org).
# All rights reserved. Use is subject to license terms.
#
#
# Contributors list :
#
#    William Bonnet     wllmbnnt@gmail.com, wbonnet@theitmakers.com
#
#

---

# -------------------------------------------------------------------------------------------------
# Create the ftpsync group
- name: Create the ftpsync group
  group: name={{ dft_srv_ftpsync.user_definition.group | default('ftpsync')}}
         state=present

# Add the user 'ftpsync' with a bash shell, appending the group ftpsync and
# {{ dft_srv_ftpsync.webserver_definition.group }} to the user's groups
- name: Create the ftpsync user
  user: name={{ dft_srv_ftpsync.user_definition.username | default('ftpsync') }}
        shell={{ dft_srv_ftpsync.user_definition.shell | default('/bin/bash')}}
        home={{ dft_srv_ftpsync.user_definition.home_dir | default('/home/ftpsync')}}
        group={{ dft_srv_ftpsync.user_definition.group | default('ftpsync') }}
        groups={{ dft_srv_ftpsync.user_definition.groups | default('ftpsync') }}
        append=yes

# Create the ftpsync script directory
- name: DFT - Create ftpsync home directory
  file: path={{ dft_srv_ftpsync.user_definition.home_dir | default('/home/ftpsync') }}/bin
        state=directory
        recurse=yes
        owner={{ dft_srv_ftpsync.user_definition.username }}
        group={{ dft_srv_ftpsync.user_definition.group }}
        mode="0755"

# Create the ftpsync log directory
- name: DFT - Create ftpsync log directory
  file: path=/var/log/ftpsync
        state=directory
        owner={{ dft_srv_ftpsync.user_definition.username }}
        group={{ dft_srv_ftpsync.user_definition.group }}
        mode="0750"

#
# Create the ftpsync configuration file
#
- name : DFT - Generate ftpsync configuration file
  template:  src=ftpsync.conf.j2
             dest=/etc/ftpsync.conf
             owner=root
             group=root
             mode="0644"
  when: dft_srv_ftpsync.config_file is defined
