#
# The contents of this file are subject to the Apache 2.0 license you may not
# use this file except in compliance with the License.
#
# Software distributed under the License is distributed on an "AS IS" basis,
# WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
# for the specific language governing rights and limitations under the
# License.
#
#
# Copyright 2016 DFT project (http://www.firmwaretoolkit.org).
# All rights reserved. Use is subject to license terms.
#
#
# Contributors list :
#
#    William Bonnet     wllmbnnt@gmail.com, wbonnet@theitmakers.com
#
#

#
# Include the list of specific tasks. Tasks are separated into different
# files, one file per functionnality.
#

---
- name : DFT - Install timezone data
  apt:
       pkg=tzdata
       state=latest
       install_recommends=no

# Use the timezone module if it does not run on a local connection, otherwise bus is not available
- name: DFT - Configure timezone (non local connection)
  timezone: name={{ dft_timezone }}
  when: ansible_connection != "local"

# If it is run through a local connection, we assume it is working in a chrooted environment
# thus only modify /etc/hostname file since timedatectl will not be able to connect to the bus
- name: DFT - Configure timezone (local connection)
  template:  src=timezone.j2
             dest=/etc/timezone
             owner=root
             group=root
             mode="0644"
  when: ansible_connection == "local"
