#!/bin/bash

# Set working directory to ftpsync home
cd ${HOME}

# Source the synchronize all configuration file
source ${HOME}/etc/ftpsync-synchronize-all-archives.conf

# Synchronize security archive
if [ ${SYNCHRONIZE_ALL_ARCHIVES_DO_SYNCHRONIZE_SECURITY} -eq 1 ] ;
then
  echo "$(date +"%Y-%m-%d %H:%M:%S") : Synchronization starting : security"
  ${HOME}/bin/ftpsync sync:all sync:archive:security
  echo "$(date +"%Y-%m-%d %H:%M:%S") : Synchronization finished : security"
fi

# Synchronize main archive
if [ ${SYNCHRONIZE_ALL_ARCHIVES_DO_SYNCHRONIZE_MAIN} -eq 1 ] ;
then
  echo "$(date +"%Y-%m-%d %H:%M:%S") : Synchronization starting : debian"
  ${HOME}/bin/ftpsync
  echo "$(date +"%Y-%m-%d %H:%M:%S") : Synchronization finished : debian"
fi

# Synchronize ports archive
if [ ${SYNCHRONIZE_ALL_ARCHIVES_DO_SYNCHRONIZE_PORTS} -eq 1 ] ;
then
  echo "$(date +"%Y-%m-%d %H:%M:%S") : Synchronization starting : debian-ports"
  ${HOME}/bin/ftpsync sync:all sync:archive:ports
  echo "$(date +"%Y-%m-%d %H:%M:%S") : Synchronization finished : debian-ports"
fi
