#
# The contents of this file are subject to the Apache 2.0 license you may not
# use this file except in compliance with the License.
#
# Software distributed under the License is distributed on an "AS IS" basis,
# WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
# for the specific language governing rights and limitations under the
# License.
#
#
# Copyright 2016 DFT project (http://www.debianfirmwaretoolkit.org).
# All rights reserved. Use is subject to license terms.
#
# Debian Firmware Toolkit is the new name of Linux Firmware From Scratch
# Copyright 2014 LFFS project (http://www.linuxfirmwarefromscratch.org).
#
#
# Contributors list :
#
#    William Bonnet     wllmbnnt@gmail.com, wbonnet@theitmakers.com
#
#

#
# This variable control the generation of the /etc/apt/apt.conf.d/10no-check-valid-until file
# This file (if generated) will deactivate repository age control, allowing to use repositories
# with invalid (meaning too old) last synchronization date.
#
# This is useful when your main repository is not automatically updated from an online official
# repository. Default value is to generate this file and deactivate the check
#
dft_os_apt_deactivate_check_valid_until: True

#
# This variable control the generation of the /etc/apt/sources.list file
# This file is the main repository sources list. It should contain only the url of the Debian
# mirrors used by the system. The rest of the sources files goes to /etc/apt/sources.list.d
#
# Default value is to generate this file
#
dft_os_apt_generate_source_list: True

#
# This variable defines the main Debian mirror used by the system
#
dft_os_apt_debian_mirror: http://ftp.de.debian.org

#
# This variable defines if the deb-src sources should be generated of not
#
dft_os_apt_generate_deb_src: False

#
# This variable controls the version of debian which is used
#
dft_os_apt_debian_version: stretch

#
# This variable controls the sections of debian distribution which are used
#
dft_os_apt_debian_sections: main
