#
# The contents of this file are subject to the Apache 2.0 license you may not
# use this file except in compliance with the License.
#
# Software distributed under the License is distributed on an "AS IS" basis,
# WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
# for the specific language governing rights and limitations under the
# License.
#
#
# Copyright 2016 DFT project (http://www.debianfirmwaretoolkit.org).
# All rights reserved. Use is subject to license terms.
#
# Debian Firmware Toolkit is the new name of Linux Firmware From Scratch
# Copyright 2014 LFFS project (http://www.linuxfirmwarefromscratch.org).
#
#
# Contributors list :
#
#    William Bonnet     wllmbnnt@gmail.com, wbonnet@theitmakers.com
#
#

#
# Include the list of specific tasks. Tasks are separated into different
# files, one file per functionnality.
#

---
# Installation of the fillewall itself
- name : DFT - Install shorewall
  apt: name={{ item }}
       state=latest
       install_recommends=no
  with_items:
    - shorewall

# Generate the content of the /etc/default/shorewall files from template
# This files control several global variables, including startup at boot
- name: DFT - Configure /etc/default/shorewall
  template: src=default-shorewall.j2
            dest=/etc/default/shorewall
            owner=root
            group=root
            mode="0640"
  when: dft_shorewall is defined and dft_shorewall.default is defined

# Generate the content of the /etc/shorewall/params files from template
# This files defines global variables for the shorewall frontend (to iptables)
- name: DFT - Configure /etc/shorewall/params
  template: src=params.j2
            dest=/etc/shorewall/params
            owner=root
            group=root
            mode="0640"
  when: dft_shorewall is defined and dft_shorewall.params is defined

# Generate the content of the /etc/shorewall/policy files from template
# This files defines the policy (ACCEPT, REJECT, DROP, etc.) between the diffrent zones
- name: DFT - Configure /etc/shorewall/policy
  template: src=policy.j2
            dest=/etc/shorewall/policy
            owner=root
            group=root
            mode="0640"
  when: dft_shorewall is defined and dft_shorewall.policy is defined

# Generate the content of the /etc/shorewall/interfaces files from template
# This files defines the interfaces managened by the firewall (eth0, eth1, etc.)
- name: DFT - Configure /etc/shorewall/interfaces
  template: src=interfaces.j2
            dest=/etc/shorewall/interfaces
            owner=root
            group=root
            mode="0640"
  when: dft_shorewall is defined and dft_shorewall.interfaces is defined

# Generate the content of the /etc/shorewall/masq files from template
# This files defines which interface are masqueraded
- name: DFT - Configure /etc/shorewall/masq
  template: src=masq.j2
            dest=/etc/shorewall/masq
            owner=root
            group=root
            mode="0640"
  when: dft_shorewall is defined and dft_shorewall.masq is defined

# Generate the content of the /etc/shorewall/rules files from template
# This files defines the firewalling rules
- name: DFT - Configure /etc/shorewall/rules
  template: src=rules.j2
            dest=/etc/shorewall/rules
            owner=root
            group=root
            mode="0640"
  when: dft_shorewall is defined and dft_shorewall.rules is defined

# Generate the content of the /etc/shorewall/shorewall.conf files from template
# This files defines the firewall scripts variables values
- name: DFT - Configure /etc/shorewall/shorewall.conf
  template: src=shorewall.conf.j2
            dest=/etc/shorewall/shorewall.conf
            owner=root
            group=root
            mode="0640"
  when: dft_shorewall is defined and dft_shorewall.shorewall_conf is defined

# Generate the content of the /etc/shorewall/stoppedrules files from template
# This files defines what traffic goes through the firewall when it is in the stopped state
- name: DFT - Configure /etc/shorewall/stoppedrules
  template: src=stoppedrules.j2
            dest=/etc/shorewall/stoppedrules
            owner=root
            group=root
            mode="0640"
  when: dft_shorewall is defined and dft_shorewall.stopped_rules is defined

# Generate the content of the /etc/shorewall/zones files from template
# This files defines the zones managed by the firewall
- name: DFT - Configure /etc/shorewall/zones
  template: src=zones.j2
            dest=/etc/shorewall/zones
            owner=root
            group=root
            mode="0640"
  when: dft_shorewall is defined and dft_shorewall.zones is defined
