#
# The contents of this file are subject to the Apache 2.0 license you may not
# use this file except in compliance with the License.
#
# Software distributed under the License is distributed on an "AS IS" basis,
# WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
# for the specific language governing rights and limitations under the
# License.
#
#
# Copyright 2016 DFT project (http://www.firmwaretoolkit.org).
# All rights reserved. Use is subject to license terms.
#
#
# Contributors list :
#
#    William Bonnet     wllmbnnt@gmail.com, wbonnet@theitmakers.com
#
#

---

#
# Install Xfce packages needed to have a desktop session
#
- name: Install XFCE4 session and desktop
  apt: name={{ item }}
       state=latest
       install_recommends=no
  with_items:
#    - xfwm4
#    - xfce4-settings
#    - libxfce4ui-utils
#    - xfce4-session
    - xfce4
    - xfce4-terminal

#
# If activated, install unclutter to hide mouse pointer
#
- name: Install unclutter
  apt: name=unclutter
       state=latest
       install_recommends=no
  when: ( dft_unclutter is defined and dft_unclutter == True )

#
# And set unclutter idle delay before it hides the mouse pointer (in seconds)
#
# - name: Configure unclutter
#       dft_unclutter_idle: 1

# => goes to .xinitrc ? or .dftrc running everything ?
# need to take it out of xfce
