#
# The contents of this file are subject to the Apache 2.0 license you may not
# use this file except in compliance with the License.
#
# Software distributed under the License is distributed on an "AS IS" basis,
# WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
# for the specific language governing rights and limitations under the
# License.
#
#
# Copyright 2016 DFT project (http://www.debianfirmwaretoolkit.org).
# All rights reserved. Use is subject to license terms.
#
# Debian Firmware Toolkit is the new name of Linux Firmware From Scratch
# Copyright 2014 LFFS project (http://www.linuxfirmwarefromscratch.org).
#
#
# Contributors list :
#
#    William Bonnet     wllmbnnt@gmail.com, wbonnet@theitmakers.com
#
#

#
# Include the list of specific tasks. Tasks are separated into different
# files, one file per functionnality.
#

---
- name : DFT - Install bind9
  apt: name={{ item }}
       state=latest
       install_recommends=no
  with_items:
    - bind9

- name : DFT - Setup bind9 zones
  template: src=templates/zone.j2
            dest=/etc/bind/db.{{ dft_dns_server["zone"]["filename"] }}
            owner=root
            group=root
            mode="u=rw,g=r,o=r"

- name : DFT - Setup bind9 reverse zones
  template: src=templates/reverse.j2
            dest=/etc/bind/reverse.{{ dft_dns_server["zone"]["filename"] }}
            owner=root
            group=root
            mode="u=rw,g=r,o=r"

- name : DFT - Setup bind9 logging configuration
  copy: src=files/named.conf.log
        dest=/etc/bind/named.conf.log
        owner=root
        group=root
        mode="u=rw,g=r,o=r"

- name : DFT - Create bind9 logging directory
  file: dest=/var/log/bind
        state=directory
        owner=bind
        group=bind
        mode="u=rwx,g=rx,o=rx"

- name: DFT - Add log configuration to named.conf
  lineinfile: dest=/etc/bind/named.conf
              state=present
              line='include "/etc/bind/named.conf.log";'

# TODO: Deplay zones in named.conf.local
# TODO: Add template for file named.conf.options
# TODO: Reload service
# TODO: add tags
# TODO: Generate key

