#
# The contents of this file are subject to the Apache 2.0 license you may not
# use this file except in compliance with the License.
#
# Software distributed under the License is distributed on an "AS IS" basis,
# WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
# for the specific language governing rights and limitations under the
# License.
#
#
# Copyright 2016 DFT project (http://www.firmwaretoolkit.org).
# All rights reserved. Use is subject to license terms.
#
#
# Contributors list :
#
#    William Bonnet     wllmbnnt@gmail.com, wbonnet@theitmakers.com
#
#

#
# Include the list of specific tasks. Tasks are separated into different
# files, one file per functionnality.
#

---
- name : DFT - Install Zabbix agent
  apt: name={{ item }}
       state=latest
       install_recommends=no
  with_items:
    - zabbix-agent

- name : DFT - Configure Zabbix agent
  template: src=templates/zabbix-agent.conf.j2
          dest=/etc/zabbix-agent/zabbix-agent.conf
          owner=root
          group=root
          mode="u=rw,g=r,o=r"
