#
# The contents of this file are subject to the Apache 2.0 license you may not
# use this file except in compliance with the License.
#
# Software distributed under the License is distributed on an "AS IS" basis,
# WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
# for the specific language governing rights and limitations under the
# License.
#
#
# Copyright 2016 DFT project (http://www.firmwaretoolkit.org).
# All rights reserved. Use is subject to license terms.
#
# Debian Firmware Toolkit is the new name of Linux Firmware From Scratch
# Copyright 2014 LFFS project (http://www.linuxfirmwarefromscratch.org).
#
#
# Contributors list :
#
#    William Bonnet     wllmbnnt@gmail.com, wbonnet@theitmakers.com
#
#

#
# Include the list of specific tasks. Tasks are separated into different
# files, one file per functionnality.
#

---
#
# Install firefox browser
#
- name : DFT - Install Firefox
  apt: name={{ item }}
       state=latest
       install_recommends=no
  with_items:
    - firefox

#
# Create the directory needed to store the firefox desktop entry
#
- name : DFT - Create desktop autostart directory
  file: path=/home/{{ dft_username }}/.config/autostart
        state=directory
        mode=0775
        recurse=yes
        owner={{ dft_username }}
        group={{ dft_usergroup }}

#
# Create the chromium desktop entry used to start firefox when session opens
#
- name : DFT - Install firefox autostart
  template: src=templates/firefox.desktop.j2
          dest=/home/{{ dft_username }}/.config/autostart/firefox.desktop
          owner={{ dft_username }}
          group={{ dft_usergroup }}
          mode="u=rw,g=r,o=r"
