#
# The contents of this file are subject to the Apache 2.0 license you may not
# use this file except in compliance with the License.
#
# Software distributed under the License is distributed on an "AS IS" basis,
# WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
# for the specific language governing rights and limitations under the
# License.
#
#
# Copyright 2020 DFT project (http://www.firmwaretoolkit.org).
# All rights reserved. Use is subject to license terms.
#
#
# Contributors list :
#
#    William Bonnet     wllmbnnt@gmail.com, wbonnet@theitmakers.com
#
#

---

#
# Activate the configuration files
#
- name: Activate apache2 enabled conf files
  command: a2enconf {{ item.name }}
  with_items: "{{ dft_apache2.conf_enabled}}"
  when: dft_apache2.conf_enabled is defined
#-  notify:
#    - restart apache

#
# Deactivate the configuration files
#
- name: Deactivate apache2 disabled conf files
  command: a2disconf {{ item.name }}
  with_items: "{{ dft_apache2.conf_disabled}}"
  when: dft_apache2.conf_disabled is defined
#-  notify:
#    - restart apache
