#
# The contents of this file are subject to the Apache 2.0 license you may not
# use this file except in compliance with the License.
#
# Software distributed under the License is distributed on an "AS IS" basis,
# WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
# for the specific language governing rights and limitations under the
# License.
#
#
# Copyright 2016 DFT project (http://www.firmwaretoolkit.org).
# All rights reserved. Use is subject to license terms.
#
#
# Contributors list :
#
#    William Bonnet     wllmbnnt@gmail.com, wbonnet@theitmakers.com
#
#

dft_dns_server:
  zone:
    filename: "dft.org"
    primary_server_name: "dft.org."
    hostmaster_email: "dft.org."
    # Serial is optional, if not defined, the serial will be generated and set
    # by default to epoch
    # serial: "1"
    refresh: "86400"
    retry: "900"
    expire: "2419200"
    minimum_ttl: "3600"
    ttl: "1D"

  dns:
    - hostname: dns1.dft.org
    - hostname: dns2.dft.org

  mx:
    - hostname: mx1.dft.org
      preference: 10
    - hostname: mx2.dft.org
      preference: 20

  hosts:
    - hostname: example1
      address: 10.0.0.1
    - hostname: example2
      address: 10.0.0.2

  cnames:
    - hostname: example3
      cname: example1
