#
# The contents of this file are subject to the Apache 2.0 license you may not
# use this file except in compliance with the License.
#
# Software distributed under the License is distributed on an "AS IS" basis,
# WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
# for the specific language governing rights and limitations under the
# License.
#
#
# Copyright 2016 DFT project (http://www.debianfirmwaretoolkit.org).
# All rights reserved. Use is subject to license terms.
#
# Debian Firmware Toolkit is the new name of Linux Firmware From Scratch
# Copyright 2014 LFFS project (http://www.linuxfirmwarefromscratch.org).
#
#
# Contributors list :
#
#    William Bonnet     wllmbnnt@gmail.com, wbonnet@theitmakers.com
#
#

dft_shorewall:
  default:
    # set the following varible to 1 in order to allow Shorewall to start
    startup: 1

    # If your Shorewall configuration requires detection of the ip address of a ppp
    # interface, you must list such interfaces in "wait_interface" to get Shorewall
    # to wait until the interface is configured. Otherwise the script will fail
    # because it won't be able to detect the IP address.
    #
    # Example:
    #    wait_interface: "ppp0"
    # wait_interface:

    # Global start/restart options
    options: ""

    # Start options
    start_options: ""

    # Restart options
    restart_options: ""

    # Init Log -- Default is /dev/null, use the STARTUP_LOG defined in shorewall.conf
    # init_log:

    # Set this to 1 to cause '/etc/init.d/shorewall stop' to place the firewall in
    # a safe state rather than to open it. Default value is 0
    # safe_stop:
