#!/bin/bash

# Set working directory to ftpsync home
cd ${HOME}

# Source the synchronize all configuration file
source ${HOME}/etc/ftpsync-synchronize-all-archives.conf

# Synchronize main archive
if [ ${SYNCHRONIZE_ALL_ARCHIVES_DO_SYNCHRONIZE_MAIN} -eq 1 ] ;
then
  ${HOME}/bin/ftpsync
fi

# Synchronize ports archive
if [ ${SYNCHRONIZE_ALL_ARCHIVES_DO_SYNCHRONIZE_PORTS} -eq 1 ] ;
then
  ${HOME}/bin/ftpsync sync:archive:ports
fi

# Synchronize backports archive
if [ ${SYNCHRONIZE_ALL_ARCHIVES_DO_SYNCHRONIZE_BACKPORTS} -eq 1 ] ;
then
  ${HOME}/bin/ftpsync sync:archive:backports
fi

# Synchronize security archive
if [ ${SYNCHRONIZE_ALL_ARCHIVES_DO_SYNCHRONIZE_SECURITY} -eq 1 ] ;
then
  ${HOME}/bin/ftpsync sync:archive:security
fi

