#!/bin/bash

# Set working directory to ftpsync home
cd ${HOME}

# Source the synchronize all configuration file
source ${HOME}/etc/synchronize-all-archives.cfg

# Synchronize main archive
if [ ${SYNCHRONIZE_ALL_ARCHIVES_DO_SYNCHRONIZE_MAIN} -eq 1 ] ;
then
  ${HOME}/bin/ftpsync
fi

# Iterate the list of other archives
for ARCHIVE in backports security ports do ;
  if [ ${SYNCHRONIZE_ALL_ARCHIVES_DO_SYNCHRONIZE_${ARCHIVE}} -eq 1 ] ;
  then
    ${HOME}/bin/ftpsync sync:archive:${ARCHIVE}
  fi
done
