# ----------------------------------------------------------------------------
#
# Definition of the distributions used to bootstrap firmware construction
#
distributions :
    # Debian 8.0 Jessie
    - name: 'jessie'
      architecture: [ 'amd64', 'i386', 'armel', 'armhf' ]
      repositories:
        - url: 'http://ftp.fr.debian.org/debian/'
          suite: 'jessie'
          sections : [ 'main' , 'contrib' , 'non-free' ]
        - url: 'http://security.debian.org/debian/'
          suite: 'jessie/updates'
          sections: [ 'main', 'contrib', 'non-free' ]
        - url: 'http://ftp.fr.debian.org/debian/'
          suite: 'jessie-updates'
          sections: [ 'main', 'contrib', 'non-free' ]
