#
# The contents of this file are subject to the Apache 2.0 license you may not
# use this file except in compliance with the License.
#
# Software distributed under the License is distributed on an "AS IS" basis,
# WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
# for the specific language governing rights and limitations under the
# License.
#
#
# Copyright 2020 DFT project (http://www.firmwaretoolkit.org).
# All rights reserved. Use is subject to license terms.
#
#
# Contributors list :
#
#    William Bonnet     wllmbnnt@gmail.com, wbonnet@theitmakers.com
#
#

---
- name: Create filesystems on physical devices
  filesystem:
    dev: "{{ item.dev }}"
    force: "{{ item.force | default(False) }}"
    fstype: "{{ item.fstype }}"
    opts: "{{ item.opts | default() }}"
    resizefs: "{{ item.resizefs }}"
  with_items: "{{ dft_os_filesystem.devices }}"
  when : dft_os_filesystem is defined