#
# The contents of this file are subject to the Apache 2.0 license you may not
# use this file except in compliance with the License.
#
# Software distributed under the License is distributed on an "AS IS" basis,
# WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
# for the specific language governing rights and limitations under the
# License.
#
#
# Copyright 2016 DFT project (http://www.firmwaretoolkit.org).
# All rights reserved. Use is subject to license terms.
#
#
# Contributors list :
#
#    William Bonnet     wllmbnnt@gmail.com, wbonnet@theitmakers.com
#
#

#
# Common installation tasks to get a ftpsync up and running
#

---
- include-tasks: "{{ dft_playbook_logger }}/tasks/logging.yml"
  when: dft_playbook_logger is defined

# Create the ftpsync group
- name: Create the ftpsync group
  group: name={{ dft_ftpsync_user_group }} state=present

# Add the user 'ftpsync' with a bash shell, appending the group 'ftpsync' to the user's groups
- name: Create the ftpsync user
  user: name={{ dft_ftpsync_user_username }}
        shell={{ dft_ftpsync_user_shell }}
        home={{ dft_ftpsync_user_home_dir }}
        groups={{ dft_ftpsync_user_group }}
        append=yes

- name: Install Apache2 Web server and rsync
  apt: name={{ item }}
       state=latest
       install_recommends=no
  with_items:
    - apache2
    - rsync

# Create the main archive target directory
- name: Create the main archive target directory
  file: path={{ dft_ftpsync_main_repository_dir }}
        state=directory
        mode=0775
        group={{ dft_ftpsync_user_group }}
        owner={{ dft_ftpsync_user_username }}

# Create the ports archive target directory
- name: Create the ports archive target directory
  file: path={{ dft_ftpsync_ports_repository_dir }}
        state=directory
        mode=0775
        group={{ dft_ftpsync_user_group }}
        owner={{ dft_ftpsync_user_username }}

# Create the security archive target directory
- name: Create the security archive target directory
  file: path={{ dft_ftpsync_security_repository_dir }}
        state=directory
        mode=0775
        group={{ dft_ftpsync_user_group }}
        owner={{ dft_ftpsync_user_username }}

# Download the ftpsync archive
- name: Get ftp sync and extract archive
  unarchive: src=https://ftp-master.debian.org/ftpsync.tar.gz dest=/tmp copy=no

# Ensure log dir exists (it happens it may be removed from Debian archive)
- name: Ensure the log dir exist
  file: path=/tmp/distrib/log
        state=directory
        mode=0755
        group=root
        owner=root

# Copy the extract files to the ftpsync user home directory
- name: Copy the extracted files to usr/local
  command: cp -fr /tmp/distrib/{{item}} {{ dft_ftpsync_user_home_dir }}/
  with_items:
    - bin
    - etc
    - log
    - README

# Chown ownership of files in ftpsync homedir
- name: Change the ownship of ftpsync homedir files and dirs
  file: path={{ dft_ftpsync_user_home_dir }}
        group=ftpsync
        owner=ftpsync
        recurse=yes

# Clean the distrib dir from /tmp
- name: Delete the distrib dir after copying to user
  file: path=/tmp/distrib state=absent

# Copy the ftpsync main archive configuration file to target host
- name: Copy ftpsync main archive configuration file to target host
  template: src=templates/ftpsync.conf.j2
            dest={{ dft_ftpsync_user_home_dir }}/etc/ftpsync.conf
            owner=ftpsync
            group=ftpsync
            mode="u=rw,g=r,o=r"

# Copy the ftpsync security archive configuration file to target host
- name: Copy ftpsync security archive configuration file to target host
  template: src=templates/ftpsync-security.conf.j2
            dest={{ dft_ftpsync_user_home_dir }}/etc/ftpsync-security.conf
            owner=ftpsync
            group=ftpsync
            mode="u=rw,g=r,o=r"

# Copy the ftpsync ports archive configuration file to target host
- name: Copy ftpsync ports archive configuration file to target host
  template: src=templates/ftpsync-ports.conf.j2
            dest={{ dft_ftpsync_user_home_dir }}/etc/ftpsync-ports.conf
            owner=ftpsync
            group=ftpsync
            mode="u=rw,g=r,o=r"

# Copy the ftpsync-synchronize-all-archives script to target host
- name: Copy ftpsync-synchronize-all-archives script to target host
  copy:     src=files/ftpsync-synchronize-all-archives
            dest={{ dft_ftpsync_user_home_dir }}/bin/ftpsync-synchronize-all-archives
            owner=ftpsync
            group=ftpsync
            mode="u=rwx,g=rx,o=rx"

# Copy the ftpsync-synchronize-all-archives configuration file to target host
- name: Copy ftpsync-synchronize-all-archives-configuration file to target host
  template: src=templates/ftpsync-synchronize-all-archives.conf.j2
            dest={{ dft_ftpsync_user_home_dir }}/etc/ftpsync-synchronize-all-archives.conf
            owner=ftpsync
            group=ftpsync
            mode="u=rw,g=r,o=r"

# Add ftpsync to cron table for user ftpsync. Scheduled every 12 hours.
- cron: name="Repository update"
        month={{dft_ftpsync_cron_month}}
        weekday={{dft_ftpsync_cron_weekday}}
        day={{dft_ftpsync_cron_day}}
        hour={{dft_ftpsync_cron_hour}}
        minute={{dft_ftpsync_cron_minute}}
        user="{{ dft_ftpsync_user_username }}"
        job="cd {{ dft_ftpsync_user_home_dir }}/ && {{ dft_ftpsync_user_home_dir }}/bin/ftpsync-synchronize-all-archives"

# Copy the Apache vhost configuration file to target host
- name: Copy Apache vhost configuration file to target host
  template: src=templates/001-ftpsync-debian-mirror.conf.j2
            dest=/etc/apache2/sites-available/001-ftpsync-debian-mirror.conf
            owner=root
            group=root
            mode="u=rw,g=r,o=r"

# Enable the Apache vhost
- name: Enable the Apache vhost
  command: a2ensite 001-ftpsync-debian-mirror

# Restart the Apache configuration
- name: Restart the Apache configuration
  service: name=apache2 state=restarted
