#
# The contents of this file are subject to the Apache 2.0 license you may not
# use this file except in compliance with the License.
#
# Software distributed under the License is distributed on an "AS IS" basis,
# WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
# for the specific language governing rights and limitations under the
# License.
#
#
# Copyright 2020 DFT project (http://www.firmwaretoolkit.org).
# All rights reserved. Use is subject to license terms.
#
#
# Contributors list :
#
#    William Bonnet     wllmbnnt@gmail.com, wbonnet@theitmakers.com
#
#

# Generate /etc/fstab file
- name: Generate /etc/default/isc-dhcp-server.default.j2
  template:
    src: isc-dhcp-server.default.j2
    dest: /etc/default/isc-dhcp-server
    owner: root
    group: root
    mode: "0644"

  # Excute this task only if a fstab variable is defined
  when: dft_network_isc_dhcp_server is defined

# Generate /etc/fstab file
- name: Generate /etc/dhcp/dhcpd.conf
  template:
    src: dhcpd.conf.j2
    dest: /etc/dhcp/dhcpd.conf
    owner: root
    group: root
    mode: "0644"

  # Excute this task only if a fstab variable is defined
  when: dft_network_isc_dhcp_server is defined and dft_network_isc_dhcp_server.dhcpd is defined
