#
# The contents of this file are subject to the Apache 2.0 license you may not
# use this file except in compliance with the License.
#
# Software distributed under the License is distributed on an "AS IS" basis,
# WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
# for the specific language governing rights and limitations under the
# License.
#
#
# Copyright 2016 DFT project (http://www.firmwaretoolkit.org).
# All rights reserved. Use is subject to license terms.
#
#
# Contributors list :
#
#    William Bonnet     wllmbnnt@gmail.com, wbonnet@theitmakers.com
#
#

#
# Include the list of specific tasks. Tasks are separated into different
# files, one file per functionnality.
#

---
- name : DFT - Create /srv/nfs directory
  file: path=/srv/nfs
        state=directory
        mode=0755
        owner=root
        group=root

- name : DFT - Setup /etc/exports
  template: src=templates/exports.j2
            dest=/etc/exports
            owner=root
            group=root
            mode="u=rw,g=r,o=r"
