#!/bin/bash

# Retrieves the system load
system_load=$(LC_ALL=C uptime | rev | cut -f2 -d, | rev | tr -d \  )

# Retrieves the uptime
uptime=$(LC_ALL=C uptime | cut -d, -f1 | cut -d\  -f4- | sed -e "s/^ +//" )

# Retrieves the number of users
user_count=$(uptime | awk 'match($0, /[0-9]+ user[s]?,/) { print substr($0,RSTART,RLENGTH-1) } ')

# Retrieves the memory used
used_mem=$(free -h | grep "^Mem:" | awk '{ print $3 " of " $2}')

# Retrieves the swap used
used_swap=$(free -h | grep "^Swap:" | awk '{ print $2 }')
if [ "${used_swap}" == "0B" ] ;
then
  used_swap="Deactivated"
else
  used_swap=$(free -h | grep "^Swap:" | awk '{ print $3 " of " $2}')
fi

# Retrieves the root usage
used_rootfs="$(df -h / | tail -n 1 | awk '{ print $5 " of " $2}')"

# Retrieves the main IP
main_ip="192.18.1.2"

# Retrieves the CPU temp
cpu_temp="32"

printf "\n"
printf "System load: %-15s Uptime:     %-15s Users     : %s\n" "${system_load}" "${uptime}" "${user_count}"
printf "Memory used: %-15s Swap used:  %-15s Usage of /: %s\n" "${used_mem}" "${used_swap}" "${used_rootfs}"
#printf "IP: %-15s   CPU temp:   %3d °C\n" "${main_ip}" "${cpu_temp}"
